### ISSUE TITLE
Error When Run On MacOS

### ISSUE THREAD

**Issue by MCJEModder2026** [wagyourtail/JsMacros-JEP#1]
I installed JEP with pip3.10 and was struggling to get JsMacros to find it
when it did, i got that error when I tried to use it
```
ImportError: cannot import name 'java_import_hook' from 'jep' (unknown location)
at ‹module› (<string> 1:?)
```
This message appears in chat when the receive chat message (or whatever that is) is triggered and goes to a python script that just logs 'sus' to the chat

**Comment by wagyourtail** [comment]
did you install jep to a venv or something? it looks like it can't find the python-side pip install

**Comment by MCJEModder2026** [comment]
do I need to install it as sudo?
would `sudo pipin jep` work?
( `alias pipin=“pip install”` is in my zshrc)

**Comment by wagyourtail** [comment]
maybe

**Comment by MCJEModder2026** [comment]
Ok I fixed it I just didn’t direct it to the one in the system install of jep

**Comment by MCJEModder2026** [comment]
Idea: possibly add some troubleshooting for jep on Mac

**Comment by wagyourtail** [comment]
well, if I had a mac maybe I could.
